language: java
jdk:
  - oraclejdk8
node_js:
  - 6
services:
  - mysql
before_install:
  - gem install bundler
  - pip install --user codecov
install:
  - bundle install
  - cd pdp-gui && nvm install $(cat .node-version) && npm install && cd ..
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
  - mysql -e "create database IF NOT EXISTS pdpserver; grant all on pdpserver.* to 'root';SET GLOBAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;" -uroot
script:
  - mvn test
  - cd pdp-gui && nvm install $(cat .node-version) && npm run lint
after_success:
  - codecov

