language: java
jdk:
- oraclejdk8
dist: trusty
node_js:
  - '7'
services:
  - mysql
cache:
  directories:
  - node_modules
before_install:
  - pyenv global system 3.6
  - pip3 install --user codecov
  - nvm install 7
install:
  - cd pdp-gui && sh ./build.sh && cd ..
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
  - mysql -e "create database IF NOT EXISTS pdpserver; grant all on pdpserver.* to 'root';SET GLOBAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;" -uroot
script:
  - mvn test
  - cd pdp-gui && sh ./build.sh
after_success:
  - codecov
