language: java
jdk:
  - oraclejdk8
services:
  - mysql
before_install:
  - pip install --user codecov
  - mysql -e "create database IF NOT EXISTS pdpserver; grant all on pdpserver.* to 'travis';" -uroot
  - cd ./pdp-gui && gem install sass && cd ..
  - cd ./pdp-gui && gem install sass-globbing && cd ..
  - cd ./pdp-gui && gem install compass && cd ..
  - cd ./pdp-gui && npm install -g grunt-cli && cd ..
before_script:
  - cd ./pdp-gui && npm install && cd ..
after_success:
  - codecov

