language: java
jdk:
  - oraclejdk8
services:
  - mysql
before_install:
  - gem install bundler
  - pip install --user codecov
install:
  - bundle install
  - cd pdp-gui && npm install && cd ..
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
  - mysql -e "create database IF NOT EXISTS pdpserver; grant all on pdpserver.* to 'root';SET GLOBAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;" -uroot
after_success:
  - codecov

