name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  deployment:
    permissions:
      packages: write
    environment: deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: openconext-releases
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Determine the version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: versioncheck

    - name: Exit when workflow_dispatch is triggered, and the version does not contain SNAPSHOT in it's name
      run: |
        echo "Only SNAPSHOT releases can be triggered with the workflow_dispatch"
        exit 1
      if: github.event_name == 'workflow_dispatch' && ( !endsWith(steps.versioncheck.outputs.version, '-SNAPSHOT'))

    - name: Exit when a production build is triggered, and the github tag is not the same as the version in pom.xml
      run: |
        echo "Project version ${{ steps.versioncheck.outputs.version }} does not match git tag ${{ github.ref_name }}"
        exit 1
      if: github.event_name != 'workflow_dispatch' && steps.versioncheck.outputs.version != github.ref_name

    - name: Deploy with Maven
      run: mvn --batch-mode deploy -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.BUILD_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.BUILD_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the pdp gui image
      uses: docker/build-push-action@v4
      with:
        context: pdp-gui
        file: pdp-gui/docker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/openconext/openconext-pdp/pdp-gui:${{ steps.versioncheck.outputs.version }}

    - name: Build and push the pdp server image
      uses: docker/build-push-action@v4
      with:
        context: pdp-server
        file: pdp-server/docker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/openconext/openconext-pdp/pdp-server:${{ steps.versioncheck.outputs.version }}
